baseURL = "/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Amanda"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
#[[menu.main]]
#name = "Work"
#url = "#portfolio"
#weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
#[[menu.main]]
#name = "Blog"
#url = "#blog"
#weight = 6
#[[menu.main]]
#name = "Contact"
#url = "#contact"
#weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "Back to the Top"
url = "#about"
#weight = 1
#[[menu.sitemap]]
#name = "Skills"
#url = "#skills"
#weight = 2
#[[menu.sitemap]]
#name = "Work"
#url = "#"
#weight = 3
#[[menu.sitemap]]
#name = "Latest Article"
#url = "#"
#weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Amanda Bressler 2021"
footerLogo = "images/site-navigation/favicon.png"
# formspreeURL = "YOUR FORMSPREE URL"
# googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/favicon.png"

[params.address]
address = "S California Ave & Ogden Avenue Chicago, IL 60608"
email = "amanda.bressler1@gmail.com"
openingHours = "I work from 9am to 5pm on Weekdays"
phone = "Please contact me via email"

#[params.map]
#APIkey = "YOUR GOOGLE MAP API"
#latitude = "41.861063572480624"
#longitude = "-87.69496763996202"
#pinImage = "images/pin.png"

# Social icons
#[[params.social]]
#icon = "fa-facebook-official"
#url = "https://www.facebook.com/"
#weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/bressleramanda/"
weight = 2
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/amandabressler/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/_amandabressler"
weight = 4
